Repository Maven-Building-LLMS-into-Production/Cicero-LLM-Synthesizer, pull requests merged in 2023-06, with the labels that each got.

#1 Feature/initial refactoring
  .github/workflows/code-linting.yml
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .tmuxgo
  Dockerfile
  LICENSE.rst
  Makefile
  README.md
  docker/aliases.sh
  docker/docker-compose.yaml
  pyproject.toml
  requirements-deploy.txt
  requirements-dev.txt
  requirements.txt
  src/api/__init__.py
  src/api/index.py
  src/app_service/__init__.py
  src/classes/__init__.py
  src/training/__init__.py
  src/utils/__init__.py
  template.envrc
Labels: documentation, enhancement

#7 Added HuggingFace token as an environment variable to the project
  docker/docker-compose.yaml
  template.envrc
Labels: enhancement

#11 Data Preprocessing Module
  .gitignore
  .isort.cfg
  Makefile
  README.md
  docker/docker-compose.yaml
  requirements.txt
  src/classes/data_preparation.py
  src/data_processing/__init__.py
  src/data_processing/prepare_dataset.py
  src/utils/default_variables.py
  src/utils/general_utilities.py
  template.envrc
Labels: enhancement, project component

#12 Creating and uploading the Cicero datasets to HuggingFace
  .isort.cfg
  requirements.txt
  src/classes/data_preparation.py
  src/classes/hugging_face_utils.py
  src/data_processing/prepare_dataset.py
  src/utils/default_variables.py
  template.envrc
Labels: enhancement, project component

#14 Temporarily creating the dataset for the Cicero dataset with summaries
  README.md
  src/data_processing/prepare_dataset.py
  src/utils/general_utilities.py
Labels: enhancement

#15 add absa module
  src/classes/absa.py
Labels: project component

#20 Updated code to fix the code linting of the project
  .gitignore
  .isort.cfg
  src/classes/absa.py
Labels: enhancement

#21 Fixing Gradio app when running the service within Docker
  Dockerfile
  README.md
  docker/docker-compose.yaml
  src/app_service/app.py
  template.envrc
Labels: bug, enhancement
